---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords: clone strategy 
summary: 클론 복제 전략을 정의하면 데이터베이스를 성공적으로 복제할 수 있습니다. 
---
= SQL Server에 대한 클론 생성 전략을 정의합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클론 복제 전략을 정의하면 데이터베이스를 성공적으로 복제할 수 있습니다.

. 클론 작업과 관련된 제한 사항을 검토합니다.
. 필요한 클론 유형을 결정합니다.




== 클론 작업의 제한 사항

데이터베이스를 클론 복제하기 전에 클론 작업의 제한 사항을 숙지해야 합니다.

* 11.2.0.4 ~ 12.1.0.1의 Oracle 버전을 사용하는 경우 복제 작업은 에서 수행됩니다
_renamedg_ 명령을 실행할 때 중단된 상태입니다. Oracle 패치 19544733을 적용할 수 있습니다
이 문제를 해결하려면 다음을 수행합니다.
* 를 사용하여 호스트에 직접 연결된 LUN에서 데이터베이스 클론 생성
VMDK 또는 동일한 RDM LUN에 대한 Windows 호스트의 Microsoft iSCSI Initiator입니다
Windows 호스트 또는 다른 Windows 호스트는 지원되지 않습니다.
* 볼륨 마운트 지점의 루트 디렉토리는 공유 디렉토리일 수 없습니다.
* 클론이 포함된 LUN을 새 볼륨으로 이동하면 클론을 삭제할 수 없습니다.




== 클론 작업의 유형입니다

SnapCenter를 사용하여 SQL Server 데이터베이스 백업 또는 운영 데이터베이스를 복제할 수 있습니다.

* 데이터베이스 백업에서 복제합니다
+
복제된 데이터베이스는 새 응용 프로그램을 개발하고 격리하는 데 있어 기준 역할을 할 수 있습니다
운영 환경에서 발생하는 애플리케이션 오류입니다. 복제된 데이터베이스도 일 수 있습니다
소프트 데이터베이스 오류로부터 복구하는 데 사용됩니다.

* 클론 라이프사이클
+
SnapCenter를 사용하여 운영 시 발생할 반복 클론 작업을 예약할 수 있습니다
데이터베이스가 사용 중이 아닙니다.


